// MCP JSON-RPC 2.0 Basic Types

export interface JsonRpcRequest {
  jsonrpc: '2.0';
  id: number | string | null;
  method: string;
  params?: Record<string, unknown>;
}

export interface JsonRpcResponse {
  jsonrpc: '2.0';
  id: number | string | null;
  result?: unknown;
  error?: JsonRpcError;
}

export interface JsonRpcError {
  code: number;
  message: string;
  data?: unknown;
}

export interface McpTool {
  name: string;
  description: string;
  inputSchema: {
    type: 'object';
    properties: Record<string, unknown>;
    required?: string[];
  };
}

export interface McpServerInfo {
  name: string;
  version: string;
}

export interface McpCapabilities {
  tools?: Record<string, never>;
}

// tools/call parameters
export interface ToolCallParams {
  name: string;
  arguments: Record<string, unknown>;
}

// check_hallucination tool input
export interface HallucinationCheckInput {
  question: string;
  response: string;
  context?: string;
  // Configuration parameters (based on Verify when Uncertain)
  targetModel?: string;      // Target model (default: 'gpt-4o-mini')
  verifierModel?: string;    // Verifier model (default: 'gpt-4o-mini')
  nliModel?: string;         // NLI model (defaults to targetModel if unspecified)
  m?: number;                // Sampling count (default: 5, max 10)
  t1?: number;               // Stage 1 lower threshold (default: 0.3)
  tStar?: number;            // Stage 1 upper threshold (default: 0.7)
  t2?: number;               // Stage 2 cross-threshold (default: 0.5)
  useHuggingFaceNli?: boolean; // Whether to use Hugging Face NLI API (default: false)
}

// Hallucination detection result
export interface HallucinationCheckResult {
  is_hallucination: boolean;
  confidence: number;
  reason: string;
  flagged_parts?: string[];
  // Detailed verification process information
  details?: {
    stage: number;           // Executed stage (1 or 2)
    selfMpd: number;         // Self-consistency divergence (Self MPD)
    crossMpd?: number;       // Cross-model inconsistency (Cross MPD)
    targetSamples: string[]; // Samples generated by the target model
    verifierSamples?: string[]; // Samples generated by the verifier model
    thresholdsUsed: {
      t1: number;
      tStar: number;
      t2: number;
      m: number;
    };
  };
}

